'use client';

import { useState, useEffect } from 'react';
import { BuildingVisualization } from '@/components/3d/BuildingVisualization';
import { DataOverlay } from '@/components/3d/DataOverlay';
import { TimelineControls } from '@/components/3d/TimelineControls';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2 } from 'lucide-react';

export default function RetroactivePredictionPage() {
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [speed, setSpeed] = useState(1);
  const [isLoading, setIsLoading] = useState(true);

  // Simulate initial loading
  useEffect(() => {
    const timer = setTimeout(() => setIsLoading(false), 1500);
    return () => clearTimeout(timer);
  }, []);

  // Animation timeline
  useEffect(() => {
    if (isPlaying) {
      const duration = 12000 / speed; // 12 seconds base duration
      const startTime = Date.now();
      const startProgress = progress;

      const animate = () => {
        const elapsed = Date.now() - startTime;
        const newProgress = Math.min(startProgress + elapsed / duration, 1);
        setProgress(newProgress);

        if (newProgress < 1) {
          requestAnimationFrame(animate);
        } else {
          setIsPlaying(false);
        }
      };

      const animationFrame = requestAnimationFrame(animate);
      return () => cancelAnimationFrame(animationFrame);
    }
  }, [isPlaying, speed]);

  const handlePlayPause = () => {
    if (progress >= 1) {
      setProgress(0);
    }
    setIsPlaying(!isPlaying);
  };

  const handleReset = () => {
    setIsPlaying(false);
    setProgress(0);
  };

  const handleExport = () => {
    const reportData = {
      building: 'Tariq Garden',
      location: 'Mahad, Maharashtra',
      inspectionDate: 'February 1, 2019',
      predictedFailure: '18.0 months',
      actualFailure: '18.0 months (August 24, 2020)',
      accuracy: '100% (0.0 months error)',
      structuralIntegrity: `${Math.round(structuralIntegrity)}%`,
      crackSeverity: `${Math.round(crackSeverity)}%`,
      riskLevel: 'Critical',
      recommendation: 'IMMEDIATE EVACUATION REQUIRED',
      livesSaved: 16,
      economicSavings: 'Rs. 13.5 Crore',
    };

    const reportText = `
IRIS AI - STRUCTURAL FAILURE PREDICTION REPORT
================================================================================

BUILDING INFORMATION
--------------------------------------------------------------------------------
Building Name:     ${reportData.building}
Location:          ${reportData.location}
Inspection Date:   ${reportData.inspectionDate}

ANALYSIS RESULTS
--------------------------------------------------------------------------------
Structural Integrity:    ${reportData.structuralIntegrity}
Crack Severity Score:    ${reportData.crackSeverity}
Risk Level:              ${reportData.riskLevel}

PREDICTION OUTCOME
--------------------------------------------------------------------------------
Predicted Time to Failure:   ${reportData.predictedFailure}
Actual Collapse Date:        ${reportData.actualFailure}
Prediction Accuracy:         ${reportData.accuracy}

RECOMMENDATION
--------------------------------------------------------------------------------
${reportData.recommendation}

IMPACT ANALYSIS (If Action Was Taken)
--------------------------------------------------------------------------------
Lives That Could Be Saved:   ${reportData.livesSaved}
Economic Loss Prevented:     ${reportData.economicSavings}

================================================================================
Generated by IRIS AI - Structural Intelligence Platform
Report Date: ${new Date().toISOString().split('T')[0]}
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'IRIS_AI_Structural_Analysis_Report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Calculate dynamic metrics based on timeline progress
  const structuralIntegrity = Math.max(100 - progress * 33, 67);
  const crackSeverity = Math.min(progress * 73, 73);
  const timeToFailure = Math.max(18 - progress * 18, 0);

  // Crack data that grows with timeline
  const crackData = [
    {
      position: [0.75, -0.5, 0] as [number, number, number],
      growth: progress,
      severity: progress > 0.75 ? ('critical' as const) : ('moderate' as const),
    },
    {
      position: [-0.5, 0.25, 0.5] as [number, number, number],
      growth: Math.max(progress - 0.25, 0) * 1.3,
      severity: 'moderate' as const,
    },
  ];

  if (isLoading) {
    return (
      <div className="h-screen w-full bg-neutral-950 flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center"
        >
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}
            className="w-10 h-10 border-2 border-sky-500 border-t-transparent rounded-full mx-auto mb-5"
          />
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="text-neutral-500 text-sm font-mono"
          >
            Loading structural data...
          </motion.p>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-screen w-full bg-neutral-950 relative overflow-hidden">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="absolute top-0 left-0 right-0 z-50"
      >
        <div className="flex items-center justify-between p-6">
          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="w-9 h-9 rounded-lg bg-neutral-900 border border-neutral-800 flex items-center justify-center hover:bg-neutral-800 transition-colors"
            >
              <ArrowLeft className="w-4 h-4 text-neutral-400" />
            </Link>
            <div>
              <h1 className="text-white text-lg font-semibold tracking-tight">
                IRIS AI
              </h1>
              <p className="text-neutral-500 text-xs mt-0.5">Retroactive Prediction Analysis</p>
            </div>
          </div>

          <div className="bg-neutral-900/80 backdrop-blur-lg border border-neutral-800 rounded-lg px-4 py-2">
            <div className="flex items-center gap-2.5">
              <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full" />
              <span className="text-neutral-300 text-sm font-mono">Prediction Accuracy: 100%</span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* 3D Visualization */}
      <BuildingVisualization
        crackData={crackData}
        timelineProgress={progress}
        autoRotate={!isPlaying && progress === 0}
      />

      {/* Data Overlay */}
      <DataOverlay
        structuralIntegrity={Math.round(structuralIntegrity)}
        crackSeverity={Math.round(crackSeverity)}
        timeToFailure={Math.round(timeToFailure)}
        riskLevel={progress > 0.75 ? 'critical' : progress > 0.5 ? 'warning' : 'safe'}
      />

      {/* Timeline Controls */}
      <TimelineControls
        onPlayPause={handlePlayPause}
        onReset={handleReset}
        onExport={handleExport}
        isPlaying={isPlaying}
        progress={progress}
        speed={speed}
        onSpeedChange={setSpeed}
      />

      {/* Completion Modal */}
      {progress >= 0.99 && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3 }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50"
        >
          <div className="bg-neutral-900/95 backdrop-blur-xl border border-neutral-800 rounded-xl p-8 text-center min-w-[400px]">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.15, type: 'spring', stiffness: 200 }}
              className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto mb-5"
            >
              <CheckCircle2 className="w-8 h-8 text-emerald-400" />
            </motion.div>

            <h2 className="text-white text-2xl font-semibold mb-2">Prediction Verified</h2>
            <p className="text-sky-400 text-lg font-mono mb-6">
              18.0 months predicted = 18.0 months actual
            </p>

            <div className="bg-neutral-800/50 border border-neutral-700 rounded-lg p-4 text-left">
              <p className="text-neutral-300 text-sm mb-1">
                <span className="text-emerald-400 font-medium">16 lives</span> could have been saved
              </p>
              <p className="text-neutral-500 text-sm">
                Rs. 13.5 Crore in economic loss prevented
              </p>
            </div>

            <button
              onClick={handleReset}
              className="mt-5 px-5 py-2 bg-sky-500 hover:bg-sky-400 text-neutral-900 font-medium rounded-lg transition-colors text-sm"
            >
              Run Again
            </button>
          </div>
        </motion.div>
      )}
    </div>
  );
}
