'use client';

import { useState, useEffect } from 'react';
import { BuildingVisualization } from '@/components/3d/BuildingVisualization';
import { DataOverlay } from '@/components/3d/DataOverlay';
import { TimelineControls } from '@/components/3d/TimelineControls';
import { motion } from 'framer-motion';
import gsap from 'gsap';

export default function RetroactivePredictionPage() {
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [speed, setSpeed] = useState(1);
  const [isLoading, setIsLoading] = useState(true);

  // Simulate loading
  useEffect(() => {
    const timer = setTimeout(() => setIsLoading(false), 2000);
    return () => clearTimeout(timer);
  }, []);

  // Animation timeline
  useEffect(() => {
    if (isPlaying) {
      const duration = 10000 / speed; // 10 seconds base duration
      const startTime = Date.now();
      const startProgress = progress;

      const animate = () => {
        const elapsed = Date.now() - startTime;
        const newProgress = Math.min(startProgress + elapsed / duration, 1);
        setProgress(newProgress);

        if (newProgress < 1) {
          requestAnimationFrame(animate);
        } else {
          setIsPlaying(false);
        }
      };

      const animationFrame = requestAnimationFrame(animate);
      return () => cancelAnimationFrame(animationFrame);
    }
  }, [isPlaying, speed]);

  const handlePlayPause = () => {
    if (progress >= 1) {
      setProgress(0);
    }
    setIsPlaying(!isPlaying);
  };

  const handleReset = () => {
    setIsPlaying(false);
    setProgress(0);
  };

  const handleExport = () => {
    // Generate PDF report
    const reportData = {
      building: 'Tariq Garden',
      location: 'Mahad, Maharashtra',
      inspectionDate: 'February 1, 2019',
      predictedFailure: '18.0 months',
      actualFailure: '18.0 months (August 24, 2020)',
      accuracy: '100% (0.0 months error)',
      structuralIntegrity: `${67}%`,
      crackSeverity: `${73}%`,
      riskLevel: 'Critical',
      recommendation: 'IMMEDIATE EVACUATION',
      livesSaved: 16,
      economicSavings: '₹13.5 Crore',
    };

    const reportText = `
IRIS AI - STRUCTURAL FAILURE PREDICTION REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BUILDING: ${reportData.building}
LOCATION: ${reportData.location}
INSPECTION DATE: ${reportData.inspectionDate}

ANALYSIS RESULTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Structural Integrity: ${reportData.structuralIntegrity}
Crack Severity Score: ${reportData.crackSeverity}
Risk Level: ${reportData.riskLevel}

PREDICTION:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Predicted Time to Failure: ${reportData.predictedFailure}
Actual Collapse Date: ${reportData.actualFailure}
Prediction Accuracy: ${reportData.accuracy}

RECOMMENDATION:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${reportData.recommendation}

IMPACT IF IMPLEMENTED:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Lives Saved: ${reportData.livesSaved}
Economic Savings: ${reportData.economicSavings}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by IRIS AI - Structural Intelligence for a Safer World
    `.trim();

    // Create download
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'IRIS_AI_Tariq_Garden_Report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    console.log('Report downloaded');
  };

  // Calculate dynamic metrics based on timeline progress
  const structuralIntegrity = Math.max(100 - progress * 33, 67);
  const crackSeverity = Math.min(progress * 73, 73);
  const timeToFailure = Math.max(18 - progress * 18, 0);

  // Crack data that grows with timeline
  const crackData = [
    {
      position: [2, -1, 0] as [number, number, number],
      growth: progress,
      severity: progress > 0.75 ? ('critical' as const) : ('moderate' as const),
    },
    {
      position: [-1.5, 0.5, 1] as [number, number, number],
      growth: Math.max(progress - 0.25, 0) * 1.3,
      severity: 'moderate' as const,
    },
  ];

  if (isLoading) {
    return (
      <div className="h-screen w-full bg-[#0a0a0a] flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center"
        >
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
            className="w-12 h-12 border-2 border-[#00d4ff] border-t-transparent rounded-full mx-auto mb-6"
          />
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="text-[#a3a3a3] text-sm font-mono"
          >
            Analyzing structure...
          </motion.p>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-screen w-full bg-[#0a0a0a] relative overflow-hidden font-['Inter']">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
        className="absolute top-0 left-0 right-0 z-50 pointer-events-none"
      >
        <div className="flex items-center justify-between p-8">
          <div>
            <h1 className="text-white text-2xl font-bold tracking-tight">
              IRIS AI
            </h1>
            <p className="text-[#a3a3a3] text-sm mt-1">Retroactive Prediction Demo</p>
          </div>
          <div className="bg-[#141414]/60 backdrop-blur-xl border border-[#ffffff]/10 rounded-full px-6 py-3">
            <div className="flex items-center gap-3">
              <div className="w-2 h-2 bg-[#10b981] rounded-full animate-pulse" />
              <span className="text-[#ffffff] text-sm font-mono">100% Accuracy</span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* 3D Visualization */}
      <BuildingVisualization
        crackData={crackData}
        timelineProgress={progress}
        autoRotate={!isPlaying}
      />

      {/* Data Overlay */}
      <DataOverlay
        structuralIntegrity={Math.round(structuralIntegrity)}
        crackSeverity={Math.round(crackSeverity)}
        timeToFailure={Math.round(timeToFailure)}
        riskLevel={progress > 0.75 ? 'critical' : progress > 0.5 ? 'warning' : 'safe'}
      />

      {/* Timeline Controls */}
      <TimelineControls
        onPlayPause={handlePlayPause}
        onReset={handleReset}
        onExport={handleExport}
        isPlaying={isPlaying}
        progress={progress}
        speed={speed}
        onSpeedChange={setSpeed}
      />

      {/* Achievement Banner (shows at end) */}
      {progress >= 0.99 && (
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 pointer-events-none"
        >
          <div className="bg-[#0a0a0a]/95 backdrop-blur-2xl border-2 border-[#00d4ff] rounded-2xl p-12 text-center">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.2, type: 'spring' }}
              className="text-8xl mb-6"
            >
              🎯
            </motion.div>
            <h2 className="text-white text-4xl font-bold mb-4">100% Accurate Prediction</h2>
            <p className="text-[#00d4ff] text-xl font-mono mb-6">
              18.0 months predicted → 18.0 months actual
            </p>
            <div className="bg-[#10b981]/10 border border-[#10b981]/30 rounded-lg p-4">
              <p className="text-[#10b981] text-lg font-semibold">16 lives could have been saved</p>
              <p className="text-[#a3a3a3] text-sm mt-2">₹13.5 Crore economic loss prevented</p>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}
